-- 0005: Track the EVE SSO CharacterOwnerHash per linked character and stop
-- retaining OAuth tokens.
--
-- Generated by `drizzle-kit generate --name=account_owner_hash` from the
-- `character_owner_hash` column in src/lib/database/schema.js (the ALTER TABLE below).
-- Manually appended: the DO $$ backfill block and the token cleanup UPDATE (data-only,
-- not representable in the schema).
--
-- Why: Auth.js keys EVE accounts by CharacterID. When a character is sold or
-- transferred to another EVE account, CCP issues a new CharacterOwnerHash, but the
-- CharacterID stays the same. Without comparing the hash, the new owner would sign
-- straight into the previous owner's D-Scan Space account. src/auth.js now compares
-- the stored hash on every sign-in and session read.
--
-- Backfill: until now the Drizzle adapter stored the EVE SSO v2 access token for
-- each linked account. That token is a JWT whose payload contains
--   "sub":   "CHARACTER:EVE:<characterId>"
--   "owner": "<CharacterOwnerHash at link time>"
-- (https://docs.esi.evetech.net/docs/sso/validating_eve_jwt.html). We decode the
-- payload (no signature check needed: we issued nothing, we only read back what we
-- stored) and copy "owner" when "sub" matches the row's character. Rows that cannot
-- be decoded keep NULL and adopt the hash on their next sign-in (see src/auth.js).
--
-- Token cleanup: the app only requests the `publicData` scope and never uses the
-- stored access/refresh/id tokens, so they are cleared after the backfill. New
-- links no longer store them (adapter wrapper in src/auth.js).
ALTER TABLE "auth"."account" ADD COLUMN "character_owner_hash" text;--> statement-breakpoint
DO $$
DECLARE
	acc record;
	payload text;
	claims json;
BEGIN
	FOR acc IN
		SELECT "provider", "providerAccountId", "access_token"
		FROM "auth"."account"
		WHERE "provider" = 'eveonline'
			AND "access_token" IS NOT NULL
			AND "character_owner_hash" IS NULL
	LOOP
		BEGIN
			-- base64url -> base64 with padding
			payload := translate(split_part(acc."access_token", '.', 2), '-_', '+/');
			payload := payload || repeat('=', (4 - length(payload) % 4) % 4);
			claims := convert_from(decode(payload, 'base64'), 'UTF8')::json;

			IF claims ->> 'sub' = 'CHARACTER:EVE:' || acc."providerAccountId"
				AND coalesce(claims ->> 'owner', '') <> '' THEN
				UPDATE "auth"."account"
				SET "character_owner_hash" = claims ->> 'owner'
				WHERE "provider" = acc."provider"
					AND "providerAccountId" = acc."providerAccountId";
			END IF;
		EXCEPTION WHEN others THEN
			-- Malformed/legacy token: leave NULL, the next sign-in records the hash.
			RAISE NOTICE 'owner hash backfill skipped for character %: %', acc."providerAccountId", SQLERRM;
		END;
	END LOOP;
END $$;--> statement-breakpoint
UPDATE "auth"."account"
SET "access_token" = NULL, "refresh_token" = NULL, "id_token" = NULL
WHERE "access_token" IS NOT NULL OR "refresh_token" IS NOT NULL OR "id_token" IS NOT NULL;
