-- 0006: Model the preview/prod scan schemas in schema.js and create their missing indexes.
--
-- Generated by `drizzle-kit generate --name=model_env_scan_schemas` after schema.js started
-- modelling the scans/scan_groups tables of every environment (dev, preview, prod) instead
-- of only the DB_ENV one.
--
-- Manual edits:
-- * Removed the generated CREATE TABLE "preview"/"prod"."scan_groups"/"scans" and their
--   ADD CONSTRAINT statements: those tables and foreign keys already exist in every
--   database (created by 0001, created_by columns/FKs by 0003). Only the drizzle
--   snapshot was missing them.
-- * Kept the generated indexes (never created for preview/prod before; dev already has
--   them) and made them IF NOT EXISTS so databases patched by hand do not fail.
CREATE INDEX IF NOT EXISTS "scan_groups_public_created_idx" ON "preview"."scan_groups" USING btree ("public","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_created_by_idx" ON "preview"."scan_groups" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_public_idx" ON "preview"."scan_groups" USING btree ("public");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_created_by_public_idx" ON "preview"."scan_groups" USING btree ("created_by","public");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_group_id_idx" ON "preview"."scans" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_created_at_idx" ON "preview"."scans" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_scan_type_idx" ON "preview"."scans" USING btree ("scan_type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_created_by_idx" ON "preview"."scans" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_scan_type_created_idx" ON "preview"."scans" USING btree ("scan_type","created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_group_id_scan_type_created_idx" ON "preview"."scans" USING btree ("group_id","scan_type","created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_public_created_idx" ON "prod"."scan_groups" USING btree ("public","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_created_by_idx" ON "prod"."scan_groups" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_public_idx" ON "prod"."scan_groups" USING btree ("public");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scan_groups_created_by_public_idx" ON "prod"."scan_groups" USING btree ("created_by","public");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_group_id_idx" ON "prod"."scans" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_created_at_idx" ON "prod"."scans" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_scan_type_idx" ON "prod"."scans" USING btree ("scan_type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_created_by_idx" ON "prod"."scans" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_scan_type_created_idx" ON "prod"."scans" USING btree ("scan_type","created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scans_group_id_scan_type_created_idx" ON "prod"."scans" USING btree ("group_id","scan_type","created_by");
