-- 0007: Scan ownership FKs, timeline index, non-unique character names.
--
-- Generated by `drizzle-kit generate --name=scan_owner_set_null_and_indexes`; no manual
-- SQL edits.
-- * scans/scan_groups.created_by -> auth.user: ON DELETE SET NULL (all environments),
--   so deleting a user keeps their scans without an owner instead of failing.
-- * scans (group_id, created_at) index replaces scans(group_id) (its left prefix):
--   used by the group timeline and the "latest scan of a group" redirect.
-- * characters.name index is no longer unique: biomassed characters keep their name
--   and a live character can hold it later (inserts used to fail on the unique index).
ALTER TABLE "dev"."scan_groups" DROP CONSTRAINT "scan_groups_created_by_user_id_fk";
--> statement-breakpoint
ALTER TABLE "dev"."scans" DROP CONSTRAINT "scans_created_by_user_id_fk";
--> statement-breakpoint
ALTER TABLE "preview"."scan_groups" DROP CONSTRAINT "scan_groups_created_by_user_id_fk";
--> statement-breakpoint
ALTER TABLE "preview"."scans" DROP CONSTRAINT "scans_created_by_user_id_fk";
--> statement-breakpoint
ALTER TABLE "prod"."scan_groups" DROP CONSTRAINT "scan_groups_created_by_user_id_fk";
--> statement-breakpoint
ALTER TABLE "prod"."scans" DROP CONSTRAINT "scans_created_by_user_id_fk";
--> statement-breakpoint
DROP INDEX "dev"."scans_group_id_idx";--> statement-breakpoint
DROP INDEX "preview"."scans_group_id_idx";--> statement-breakpoint
DROP INDEX "prod"."scans_group_id_idx";--> statement-breakpoint
DROP INDEX "characters_name_idx";--> statement-breakpoint
ALTER TABLE "dev"."scan_groups" ADD CONSTRAINT "scan_groups_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dev"."scans" ADD CONSTRAINT "scans_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preview"."scan_groups" ADD CONSTRAINT "scan_groups_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preview"."scans" ADD CONSTRAINT "scans_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prod"."scan_groups" ADD CONSTRAINT "scan_groups_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prod"."scans" ADD CONSTRAINT "scans_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "scans_group_id_created_at_idx" ON "dev"."scans" USING btree ("group_id","created_at");--> statement-breakpoint
CREATE INDEX "scans_group_id_created_at_idx" ON "preview"."scans" USING btree ("group_id","created_at");--> statement-breakpoint
CREATE INDEX "scans_group_id_created_at_idx" ON "prod"."scans" USING btree ("group_id","created_at");--> statement-breakpoint
CREATE INDEX "characters_name_idx" ON "characters" USING btree ("name");