-- 0008: Convert every `timestamp without time zone` column to `timestamptz`.
--
-- Generated by `drizzle-kit generate --name=timestamptz` after schema.js switched all
-- columns to `timestamp({ withTimezone: true })` (timestamptz helper).
--
-- Manual edit: every SET DATA TYPE got `USING "<col>" AT TIME ZONE 'UTC'`. Existing
-- values were written in UTC (JS Dates serialized as ISO/UTC by drizzle, `now()` on a
-- server running TimeZone=Etc/UTC, verified on the dev database). Without USING, Postgres
-- would interpret them in the migrating session's TimeZone and could shift them.
-- The generated `SET DEFAULT now()` statements are unchanged (no-ops).
ALTER TABLE "alliances" ALTER COLUMN "last_seen" SET DATA TYPE timestamp with time zone USING "last_seen" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "alliances" ALTER COLUMN "last_seen" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "alliances" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "alliances" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "alliances" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "alliances" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "auth"."session" ALTER COLUMN "expires" SET DATA TYPE timestamp with time zone USING "expires" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "auth"."user" ALTER COLUMN "emailVerified" SET DATA TYPE timestamp with time zone USING "emailVerified" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "auth"."verificationToken" ALTER COLUMN "expires" SET DATA TYPE timestamp with time zone USING "expires" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "last_seen" SET DATA TYPE timestamp with time zone USING "last_seen" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "last_seen" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp with time zone USING "deleted_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "esi_cache_expires" SET DATA TYPE timestamp with time zone USING "esi_cache_expires" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "corporations" ALTER COLUMN "last_seen" SET DATA TYPE timestamp with time zone USING "last_seen" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "corporations" ALTER COLUMN "last_seen" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "corporations" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "corporations" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "corporations" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "corporations" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "dev"."scan_groups" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "dev"."scan_groups" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "dev"."scans" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "dev"."scans" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "inv_categories" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "inv_categories" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "inv_categories" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "inv_categories" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "inv_groups" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "inv_groups" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "inv_groups" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "inv_groups" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "inv_types" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "inv_types" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "inv_types" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "inv_types" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "preview"."scan_groups" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "preview"."scan_groups" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "preview"."scans" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "preview"."scans" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "prod"."scan_groups" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "prod"."scan_groups" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "prod"."scans" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "prod"."scans" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "sde" ALTER COLUMN "release_date" SET DATA TYPE timestamp with time zone USING "release_date" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "sde" ALTER COLUMN "release_date" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "sde" ALTER COLUMN "run_date" SET DATA TYPE timestamp with time zone USING "run_date" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "sde" ALTER COLUMN "run_date" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "systems" ALTER COLUMN "last_seen" SET DATA TYPE timestamp with time zone USING "last_seen" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "systems" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "systems" ALTER COLUMN "updated_at" SET DEFAULT now();