-- 0009: Case-insensitive character name lookups.
--
-- Generated by `drizzle-kit generate --name=characters_lower_name_index`; no manual SQL
-- edits. EVE character names are unique regardless of case and ESI's /universe/ids
-- resolves names case-insensitively, so getCharactersByName matches on lower(name).
-- The plain name index is replaced by an expression index on lower(name).
DROP INDEX "characters_name_idx";--> statement-breakpoint
CREATE INDEX "characters_name_lower_idx" ON "characters" USING btree (lower("name"));