-- 0010: Updater refresh claims.
--
-- Generated by `drizzle-kit generate --name=refresh_attempted_at`; no manual SQL edits.
-- Nullable column, no rewrite of existing rows. The updater sets it when it claims rows
-- for a refresh (FOR UPDATE SKIP LOCKED); rows whose refresh failed are retried after an
-- hour instead of being picked first again on every run.
ALTER TABLE "alliances" ADD COLUMN "refresh_attempted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "refresh_attempted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "corporations" ADD COLUMN "refresh_attempted_at" timestamp with time zone;