#:schema node_modules/wrangler/config-schema.json
name = "d-scan-updater"
main = "src/index.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[triggers]
crons = ["0 * * * *"]

d1_databases = [
	{ binding = "DB", database_name = "d-scan-database", database_id = "", preview_database_id = ""},
]

kv_namespaces = [
	{ binding = "QUERIES", id = "", preview_id = ""},
]
